version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - APP_NAME=BAG Comics
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:your_generated_app_key_here
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - SESSION_DRIVER=database
      - CACHE_STORE=database
      - QUEUE_CONNECTION=database
      - LOG_LEVEL=debug
      - STRIPE_KEY=your_stripe_publishable_key_here
      - STRIPE_SECRET=your_stripe_secret_key_here
      - VITE_STRIPE_PUBLISHABLE_KEY=your_stripe_publishable_key_here
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    restart: unless-stopped
